### ISSUE TITLE
You do not have permission

### ISSUE THREAD

**Issue by raphaelsander** [claudioandre-br/packages#15]
In the snap package it is not possible to open files in **/mnt** and **/media**. Nor is it possible to add permissions via **sudo snap connect john-the-ripper:removable-media :removable-media**.

Please add the parameters to your **snap.yaml** file:

```yaml
plugs:
    - home
    - removable-media
```

## System
snap - 2.44.3+20.04
snapd - 2.44.3+20.04
series - 16
ubuntu - 20.04
kernel - 5.4.0-31-generic
john-the-ripper - 1.9J1-a16c8a7X - 297 - latest/stable - claudioandre-b

**Comment by claudioandre-br** [comment]
Thanks, I'll look into this in a couple of days.

**Comment by claudioandre-br** [comment]
Done: https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/981049/+files/john-the-ripper_1.9J2+709e3daX_amd64.snap

After some testing, it will be available in the store.
